apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: devops-platform-dev
        metrics_path: /actuator/prometheus
        scrape_interval: 15s
        static_configs:
          - targets:
              - devops-platform.dev.svc.cluster.local:8082
            labels:
              application: devops-platform
              environment: dev

      - job_name: devops-platform-staging
        metrics_path: /actuator/prometheus
        scrape_interval: 15s
        static_configs:
          - targets:
              - devops-platform.staging.svc.cluster.local:8082
            labels:
              application: devops-platform
              environment: staging

      - job_name: devops-platform-production
        metrics_path: /actuator/prometheus
        scrape_interval: 15s
        static_configs:
          - targets:
              - devops-platform.production.svc.cluster.local:8082
            labels:
              application: devops-platform
              environment: production
